//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csmService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using csmService.Controllers;

    public partial class csmEntities : DbContext
    {
        public csmEntities()
            : base("name=csmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acceso> accesoes { get; set; }
        public virtual DbSet<alumno> alumnoes { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<materia> materias { get; set; }
        public virtual DbSet<notificacion> notificacions { get; set; }
        public virtual DbSet<profesor> profesors { get; set; }
    
        public virtual int antiguedad_cliente(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("antiguedad_cliente", idParameter);
        }
    
        public virtual ObjectResult<paginado_Result> paginado(Nullable<int> tamano, Nullable<int> numero, Nullable<sbyte> alumno)
        {
            var tamanoParameter = tamano.HasValue ?
                new ObjectParameter("tamano", tamano) :
                new ObjectParameter("tamano", typeof(int));
    
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(int));
    
            var alumnoParameter = alumno.HasValue ?
                new ObjectParameter("alumno", alumno) :
                new ObjectParameter("alumno", typeof(sbyte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paginado_Result>("paginado", tamanoParameter, numeroParameter, alumnoParameter);
        }
    
        public virtual ObjectResult<profesor_alumnos_Result> profesor_alumnos(Nullable<int> id_profesor, Nullable<int> numero, Nullable<int> tamano)
        {
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(int));
    
            var tamanoParameter = tamano.HasValue ?
                new ObjectParameter("tamano", tamano) :
                new ObjectParameter("tamano", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<profesor_alumnos_Result>("profesor_alumnos", id_profesorParameter, numeroParameter, tamanoParameter);
        }
    
        public virtual ObjectResult<buzon_Result> buzon(Nullable<int> id, Nullable<int> tamano, Nullable<int> pagina)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var tamanoParameter = tamano.HasValue ?
                new ObjectParameter("tamano", tamano) :
                new ObjectParameter("tamano", typeof(int));
    
            var paginaParameter = pagina.HasValue ?
                new ObjectParameter("pagina", pagina) :
                new ObjectParameter("pagina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buzon_Result>("buzon", idParameter, tamanoParameter, paginaParameter);
        }
    
        public virtual int crear_mensaje(Nullable<int> emisor, Nullable<int> receptor, string mensaje)
        {
            var emisorParameter = emisor.HasValue ?
                new ObjectParameter("emisor", emisor) :
                new ObjectParameter("emisor", typeof(int));
    
            var receptorParameter = receptor.HasValue ?
                new ObjectParameter("receptor", receptor) :
                new ObjectParameter("receptor", typeof(int));
    
            var mensajeParameter = mensaje != null ?
                new ObjectParameter("mensaje", mensaje) :
                new ObjectParameter("mensaje", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crear_mensaje", emisorParameter, receptorParameter, mensajeParameter);
        }
    
        public virtual ObjectResult<grupoAlumno> group_students(Nullable<int> id_profesor)
        {
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<grupoAlumno>("group_students", id_profesorParameter);
        }
    }
}
